"""Test

Revision ID: c7d199ce31a1
Revises: 
Create Date: 2025-05-06 23:31:09.259704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7d199ce31a1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=1024), nullable=False),
    sa.Column('isdisabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('disabled_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_users_email'), 'users', ['email'], unique=True, schema='public')
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('userid', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('firstname', sa.String(length=256), nullable=True),
    sa.Column('lastname', sa.String(length=256), nullable=True),
    sa.Column('sex', sa.String(length=24), nullable=True),
    sa.Column('phone', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['public.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_accounts_userid'), 'accounts', ['userid'], unique=True, schema='public')
    op.create_index(op.f('ix_public_accounts_username'), 'accounts', ['username'], unique=True, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_accounts_username'), table_name='accounts', schema='public')
    op.drop_index(op.f('ix_public_accounts_userid'), table_name='accounts', schema='public')
    op.drop_table('accounts', schema='public')
    op.drop_index(op.f('ix_public_users_email'), table_name='users', schema='public')
    op.drop_table('users', schema='public')
    # ### end Alembic commands ###
