apiVersion: apps/v1
kind: Deployment
metadata:
  name: userapi
  namespace: tasktracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userapi
  template:
    metadata:
      labels:
        app: userapi
    spec:
      containers:
        - name: userapi
          image: maksymmaliutin/userapi:latest
          env:
            - name: TEST_MODE
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: TEST_MODE
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-connection
                  key: DATABASE_URL
                  optional: true
          ports:
            - containerPort: 7000
---
apiVersion: v1
kind: Service
metadata:
  name: userapi-svc
  namespace: tasktracker
spec:
  selector:
    app: userapi
  type: NodePort
  ports:
  - port: 7000
    targetPort: 7000
    nodePort: 30001
